# Generated by Django 2.0.2 on 2020-08-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200816_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='technologies',
            new_name='technologies_used',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='My Bio!', max_length=500),
        ),
    ]
